module.exports = [
  {
    location_code: 2012,
    location_name: "Algeria",
    location_code_parent: null,
    country_iso_code: "DZ",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 24225808,
        serps: 1219644,
      },
      {
        available_sources: ["google"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 8932176,
        serps: 1133025,
      },
    ],
  },
  {
    location_code: 2024,
    location_name: "Angola",
    location_code_parent: null,
    country_iso_code: "AO",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Portuguese",
        language_code: "pt",
        keywords: 13090495,
        serps: 1523961,
      },
    ],
  },
  {
    location_code: 2031,
    location_name: "Azerbaijan",
    location_code_parent: null,
    country_iso_code: "AZ",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Azeri",
        language_code: "az",
        keywords: 13968106,
        serps: 469844,
      },
    ],
  },
  {
    location_code: 2032,
    location_name: "Argentina",
    location_code_parent: null,
    country_iso_code: "AR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 49036131,
        serps: 4166147,
      },
    ],
  },
  {
    location_code: 2036,
    location_name: "Australia",
    location_code_parent: null,
    country_iso_code: "AU",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 219702951,
        serps: 16164506,
      },
    ],
  },
  {
    location_code: 2040,
    location_name: "Austria",
    location_code_parent: null,
    country_iso_code: "AT",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "German",
        language_code: "de",
        keywords: 49314756,
        serps: 2722402,
      },
    ],
  },
  {
    location_code: 2048,
    location_name: "Bahrain",
    location_code_parent: null,
    country_iso_code: "BH",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 10538946,
        serps: 480179,
      },
    ],
  },
  {
    location_code: 2050,
    location_name: "Bangladesh",
    location_code_parent: null,
    country_iso_code: "BD",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Bengali",
        language_code: "bn",
        keywords: 26200053,
        serps: 1570547,
      },
    ],
  },
  {
    location_code: 2051,
    location_name: "Armenia",
    location_code_parent: null,
    country_iso_code: "AM",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Armenian",
        language_code: "hy",
        keywords: 1838853,
        serps: 229761,
      },
    ],
  },
  {
    location_code: 2056,
    location_name: "Belgium",
    location_code_parent: null,
    country_iso_code: "BE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 25535956,
        serps: 394243,
      },
      {
        available_sources: ["google"],
        language_name: "Dutch",
        language_code: "nl",
        keywords: 55093464,
        serps: 3184001,
      },
      {
        available_sources: ["google"],
        language_name: "German",
        language_code: "de",
        keywords: 16271689,
        serps: 807224,
      },
    ],
  },
  {
    location_code: 2068,
    location_name: "Bolivia",
    location_code_parent: null,
    country_iso_code: "BO",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 6786953,
        serps: 510921,
      },
    ],
  },
  {
    location_code: 2076,
    location_name: "Brazil",
    location_code_parent: null,
    country_iso_code: "BR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Portuguese",
        language_code: "pt",
        keywords: 121824087,
        serps: 12403546,
      },
    ],
  },
  {
    location_code: 2100,
    location_name: "Bulgaria",
    location_code_parent: null,
    country_iso_code: "BG",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Bulgarian",
        language_code: "bg",
        keywords: 6545373,
        serps: 625859,
      },
    ],
  },
  {
    location_code: 2104,
    location_name: "Myanmar (Burma)",
    location_code_parent: null,
    country_iso_code: "MM",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 12337841,
        serps: 888993,
      },
    ],
  },
  {
    location_code: 2116,
    location_name: "Cambodia",
    location_code_parent: null,
    country_iso_code: "KH",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 12337790,
        serps: 905198,
      },
    ],
  },
  {
    location_code: 2120,
    location_name: "Cameroon",
    location_code_parent: null,
    country_iso_code: "CM",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 5269651,
        serps: 468800,
      },
    ],
  },
  {
    location_code: 2124,
    location_name: "Canada",
    location_code_parent: null,
    country_iso_code: "CA",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 249183468,
        serps: 17339515,
      },
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 133976887,
        serps: 8244157,
      },
    ],
  },
  {
    location_code: 2144,
    location_name: "Sri Lanka",
    location_code_parent: null,
    country_iso_code: "LK",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 13942093,
        serps: 813787,
      },
    ],
  },
  {
    location_code: 2152,
    location_name: "Chile",
    location_code_parent: null,
    country_iso_code: "CL",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 36200315,
        serps: 1959552,
      },
    ],
  },
  {
    location_code: 2158,
    location_name: "Taiwan",
    location_code_parent: null,
    country_iso_code: "TW",
    location_type: "Region",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Chinese (Traditional)",
        language_code: "zh-TW",
        keywords: 45841170,
        serps: 4297216,
      },
    ],
  },
  {
    location_code: 2170,
    location_name: "Colombia",
    location_code_parent: null,
    country_iso_code: "CO",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 43077208,
        serps: 2237324,
      },
    ],
  },
  {
    location_code: 2188,
    location_name: "Costa Rica",
    location_code_parent: null,
    country_iso_code: "CR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 11418311,
        serps: 514559,
      },
    ],
  },
  {
    location_code: 2191,
    location_name: "Croatia",
    location_code_parent: null,
    country_iso_code: "HR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Croatian",
        language_code: "hr",
        keywords: 5997118,
        serps: 502862,
      },
    ],
  },
  {
    location_code: 2196,
    location_name: "Cyprus",
    location_code_parent: null,
    country_iso_code: "CY",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Greek",
        language_code: "el",
        keywords: 17469932,
        serps: 357124,
      },
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 13909568,
        serps: 407748,
      },
    ],
  },
  {
    location_code: 2203,
    location_name: "Czechia",
    location_code_parent: null,
    country_iso_code: "CZ",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Czech",
        language_code: "cs",
        keywords: 16901620,
        serps: 1411452,
      },
    ],
  },
  {
    location_code: 2208,
    location_name: "Denmark",
    location_code_parent: null,
    country_iso_code: "DK",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Danish",
        language_code: "da",
        keywords: 23262795,
        serps: 2428221,
      },
    ],
  },
  {
    location_code: 2218,
    location_name: "Ecuador",
    location_code_parent: null,
    country_iso_code: "EC",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 16000091,
        serps: 918870,
      },
    ],
  },
  {
    location_code: 2222,
    location_name: "El Salvador",
    location_code_parent: null,
    country_iso_code: "SV",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 6423522,
        serps: 343592,
      },
    ],
  },
  {
    location_code: 2233,
    location_name: "Estonia",
    location_code_parent: null,
    country_iso_code: "EE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Estonian",
        language_code: "et",
        keywords: 2931457,
        serps: 397555,
      },
    ],
  },
  {
    location_code: 2246,
    location_name: "Finland",
    location_code_parent: null,
    country_iso_code: "FI",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Finnish",
        language_code: "fi",
        keywords: 19607401,
        serps: 1977024,
      },
    ],
  },
  {
    location_code: 2250,
    location_name: "France",
    location_code_parent: null,
    country_iso_code: "FR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 172328897,
        serps: 17393930,
      },
    ],
  },
  {
    location_code: 2276,
    location_name: "Germany",
    location_code_parent: null,
    country_iso_code: "DE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "German",
        language_code: "de",
        keywords: 210101052,
        serps: 22662740,
      },
    ],
  },
  {
    location_code: 2288,
    location_name: "Ghana",
    location_code_parent: null,
    country_iso_code: "GH",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 8672381,
        serps: 660127,
      },
    ],
  },
  {
    location_code: 2300,
    location_name: "Greece",
    location_code_parent: null,
    country_iso_code: "GR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Greek",
        language_code: "el",
        keywords: 17283196,
        serps: 1424608,
      },
    ],
  },
  {
    location_code: 2320,
    location_name: "Guatemala",
    location_code_parent: null,
    country_iso_code: "GT",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 11721465,
        serps: 508435,
      },
    ],
  },
  {
    location_code: 2344,
    location_name: "Hong Kong",
    location_code_parent: null,
    country_iso_code: "HK",
    location_type: "Region",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 23248273,
        serps: 1254419,
      },
      {
        available_sources: ["google"],
        language_name: "Chinese (Traditional)",
        language_code: "zh-TW",
        keywords: 54693224,
        serps: 3078200,
      },
    ],
  },
  {
    location_code: 2348,
    location_name: "Hungary",
    location_code_parent: null,
    country_iso_code: "HU",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Hungarian",
        language_code: "hu",
        keywords: 12509158,
        serps: 1204907,
      },
    ],
  },
  {
    location_code: 2356,
    location_name: "India",
    location_code_parent: null,
    country_iso_code: "IN",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 195288970,
        serps: 15630590,
      },
      {
        available_sources: ["google"],
        language_name: "Hindi",
        language_code: "hi",
        keywords: 94197174,
        serps: 12308850,
      },
    ],
  },
  {
    location_code: 2360,
    location_name: "Indonesia",
    location_code_parent: null,
    country_iso_code: "ID",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 46519577,
        serps: 4073731,
      },
      {
        available_sources: ["google"],
        language_name: "Indonesian",
        language_code: "id",
        keywords: 85997991,
        serps: 6412921,
      },
    ],
  },
  {
    location_code: 2372,
    location_name: "Ireland",
    location_code_parent: null,
    country_iso_code: "IE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 50326605,
        serps: 2374185,
      },
    ],
  },
  {
    location_code: 2376,
    location_name: "Israel",
    location_code_parent: null,
    country_iso_code: "IL",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Hebrew",
        language_code: "he",
        keywords: 23095548,
        serps: 1996703,
      },
      {
        available_sources: ["google"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 11985282,
        serps: 1027989,
      },
    ],
  },
  {
    location_code: 2380,
    location_name: "Italy",
    location_code_parent: null,
    country_iso_code: "IT",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Italian",
        language_code: "it",
        keywords: 109735952,
        serps: 10652174,
      },
    ],
  },
  {
    location_code: 2384,
    location_name: "Cote d'Ivoire",
    location_code_parent: null,
    country_iso_code: "CI",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 6786132,
        serps: 709648,
      },
    ],
  },
  {
    location_code: 2392,
    location_name: "Japan",
    location_code_parent: null,
    country_iso_code: "JP",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Japanese",
        language_code: "ja",
        keywords: 211271787,
        serps: 17744020,
      },
    ],
  },
  {
    location_code: 2398,
    location_name: "Kazakhstan",
    location_code_parent: null,
    country_iso_code: "KZ",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Russian",
        language_code: "ru",
        keywords: 13804847,
        serps: 939204,
      },
    ],
  },
  {
    location_code: 2400,
    location_name: "Jordan",
    location_code_parent: null,
    country_iso_code: "JO",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 7155334,
        serps: 440941,
      },
    ],
  },
  {
    location_code: 2404,
    location_name: "Kenya",
    location_code_parent: null,
    country_iso_code: "KE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 19232887,
        serps: 1481679,
      },
    ],
  },
  {
    location_code: 2410,
    location_name: "South Korea",
    location_code_parent: null,
    country_iso_code: "KR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Korean",
        language_code: "ko",
        keywords: 45816870,
        serps: 8115207,
      },
    ],
  },
  {
    location_code: 2428,
    location_name: "Latvia",
    location_code_parent: null,
    country_iso_code: "LV",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Latvian",
        language_code: "lv",
        keywords: 8322754,
        serps: 512149,
      },
    ],
  },
  {
    location_code: 2440,
    location_name: "Lithuania",
    location_code_parent: null,
    country_iso_code: "LT",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Lithuanian",
        language_code: "lt",
        keywords: 5001607,
        serps: 527676,
      },
    ],
  },
  {
    location_code: 2458,
    location_name: "Malaysia",
    location_code_parent: null,
    country_iso_code: "MY",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 34772024,
        serps: 1998414,
      },
      {
        available_sources: ["google"],
        language_name: "Malay",
        language_code: "ms",
        keywords: 33112551,
        serps: 2612716,
      },
    ],
  },
  {
    location_code: 2470,
    location_name: "Malta",
    location_code_parent: null,
    country_iso_code: "MT",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 2772747,
        serps: 164875,
      },
    ],
  },
  {
    location_code: 2484,
    location_name: "Mexico",
    location_code_parent: null,
    country_iso_code: "MX",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 82114977,
        serps: 6666742,
      },
    ],
  },
  {
    location_code: 2504,
    location_name: "Morocco",
    location_code_parent: null,
    country_iso_code: "MA",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 9440797,
        serps: 1120632,
      },
    ],
  },
  {
    location_code: 2528,
    location_name: "Netherlands",
    location_code_parent: null,
    country_iso_code: "NL",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Dutch",
        language_code: "nl",
        keywords: 75268807,
        serps: 6286102,
      },
    ],
  },
  {
    location_code: 2554,
    location_name: "New Zealand",
    location_code_parent: null,
    country_iso_code: "NZ",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 28999567,
        serps: 1467198,
      },
    ],
  },
  {
    location_code: 2558,
    location_name: "Nicaragua",
    location_code_parent: null,
    country_iso_code: "NI",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 3527286,
        serps: 284013,
      },
    ],
  },
  {
    location_code: 2566,
    location_name: "Nigeria",
    location_code_parent: null,
    country_iso_code: "NG",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 13730145,
        serps: 1063932,
      },
    ],
  },
  {
    location_code: 2578,
    location_name: "Norway",
    location_code_parent: null,
    country_iso_code: "NO",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Norwegian (Bokmål)",
        language_code: "nb",
        keywords: 24195651,
        serps: 2838510,
      },
    ],
  },
  {
    location_code: 2586,
    location_name: "Pakistan",
    location_code_parent: null,
    country_iso_code: "PK",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 29169222,
        serps: 1335348,
      },
      {
        available_sources: ["google"],
        language_name: "Urdu",
        language_code: "ur",
        keywords: 19184021,
        serps: 437724,
      },
    ],
  },
  {
    location_code: 2591,
    location_name: "Panama",
    location_code_parent: null,
    country_iso_code: "PA",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 5352139,
        serps: 1020007,
      },
    ],
  },
  {
    location_code: 2600,
    location_name: "Paraguay",
    location_code_parent: null,
    country_iso_code: "PY",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 6006466,
        serps: 335375,
      },
    ],
  },
  {
    location_code: 2604,
    location_name: "Peru",
    location_code_parent: null,
    country_iso_code: "PE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 31112746,
        serps: 1421759,
      },
    ],
  },
  {
    location_code: 2608,
    location_name: "Philippines",
    location_code_parent: null,
    country_iso_code: "PH",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 34537345,
        serps: 1963260,
      },
      {
        available_sources: ["google"],
        language_name: "Tagalog",
        language_code: "tl",
        keywords: 32553126,
        serps: 1877374,
      },
    ],
  },
  {
    location_code: 2616,
    location_name: "Poland",
    location_code_parent: null,
    country_iso_code: "PL",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Polish",
        language_code: "pl",
        keywords: 39600809,
        serps: 3007464,
      },
    ],
  },
  {
    location_code: 2620,
    location_name: "Portugal",
    location_code_parent: null,
    country_iso_code: "PT",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Portuguese",
        language_code: "pt",
        keywords: 24945631,
        serps: 1508369,
      },
    ],
  },
  {
    location_code: 2642,
    location_name: "Romania",
    location_code_parent: null,
    country_iso_code: "RO",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Romanian",
        language_code: "ro",
        keywords: 16155625,
        serps: 1326928,
      },
    ],
  },
  {
    location_code: 2682,
    location_name: "Saudi Arabia",
    location_code_parent: null,
    country_iso_code: "SA",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google", "amazon"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 34159806,
        serps: 4412583,
      },
    ],
  },
  {
    location_code: 2686,
    location_name: "Senegal",
    location_code_parent: null,
    country_iso_code: "SN",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 4032491,
        serps: 484815,
      },
    ],
  },
  {
    location_code: 2688,
    location_name: "Serbia",
    location_code_parent: null,
    country_iso_code: "RS",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Serbian",
        language_code: "sr",
        keywords: 4803513,
        serps: 462642,
      },
    ],
  },
  {
    location_code: 2702,
    location_name: "Singapore",
    location_code_parent: null,
    country_iso_code: "SG",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 53252073,
        serps: 2384192,
      },
      {
        available_sources: ["google"],
        language_name: "Chinese (Simplified)",
        language_code: "zh-CN",
        keywords: 26286747,
        serps: 801391,
      },
    ],
  },
  {
    location_code: 2703,
    location_name: "Slovakia",
    location_code_parent: null,
    country_iso_code: "SK",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Slovak",
        language_code: "sk",
        keywords: 8503604,
        serps: 876465,
      },
    ],
  },
  {
    location_code: 2704,
    location_name: "Vietnam",
    location_code_parent: null,
    country_iso_code: "VN",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 13319538,
        serps: 1008787,
      },
      {
        available_sources: ["google"],
        language_name: "Vietnamese",
        language_code: "vi",
        keywords: 31680780,
        serps: 1511061,
      },
    ],
  },
  {
    location_code: 2705,
    location_name: "Slovenia",
    location_code_parent: null,
    country_iso_code: "SI",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Slovenian",
        language_code: "sl",
        keywords: 4861488,
        serps: 487753,
      },
    ],
  },
  {
    location_code: 2710,
    location_name: "South Africa",
    location_code_parent: null,
    country_iso_code: "ZA",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 42309192,
        serps: 2386284,
      },
    ],
  },
  {
    location_code: 2724,
    location_name: "Spain",
    location_code_parent: null,
    country_iso_code: "ES",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 132272884,
        serps: 8912981,
      },
    ],
  },
  {
    location_code: 2752,
    location_name: "Sweden",
    location_code_parent: null,
    country_iso_code: "SE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Swedish",
        language_code: "sv",
        keywords: 29953109,
        serps: 3505071,
      },
    ],
  },
  {
    location_code: 2756,
    location_name: "Switzerland",
    location_code_parent: null,
    country_iso_code: "CH",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "German",
        language_code: "de",
        keywords: 65781978,
        serps: 3271326,
      },
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 70225709,
        serps: 1498278,
      },
      {
        available_sources: ["google"],
        language_name: "Italian",
        language_code: "it",
        keywords: 6946626,
        serps: 1370138,
      },
    ],
  },
  {
    location_code: 2764,
    location_name: "Thailand",
    location_code_parent: null,
    country_iso_code: "TH",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Thai",
        language_code: "th",
        keywords: 35785149,
        serps: 3006546,
      },
    ],
  },
  {
    location_code: 2784,
    location_name: "United Arab Emirates",
    location_code_parent: null,
    country_iso_code: "AE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google", "amazon"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 30243482,
        serps: 1409082,
      },
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 32346270,
        serps: 1304549,
      },
    ],
  },
  {
    location_code: 2788,
    location_name: "Tunisia",
    location_code_parent: null,
    country_iso_code: "TN",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 7673587,
        serps: 477403,
      },
    ],
  },
  {
    location_code: 2792,
    location_name: "Turkey",
    location_code_parent: null,
    country_iso_code: "TR",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Turkish",
        language_code: "tr",
        keywords: 41618523,
        serps: 5185059,
      },
    ],
  },
  {
    location_code: 2804,
    location_name: "Ukraine",
    location_code_parent: null,
    country_iso_code: "UA",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Ukrainian",
        language_code: "uk",
        keywords: 122163703,
        serps: 11308150,
      },
      {
        available_sources: ["google"],
        language_name: "Russian",
        language_code: "ru",
        keywords: 105575497,
        serps: 5346306,
      },
    ],
  },
  {
    location_code: 2807,
    location_name: "North Macedonia",
    location_code_parent: null,
    country_iso_code: "MK",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Macedonian",
        language_code: "mk",
        keywords: 8347766,
        serps: 434245,
      },
    ],
  },
  {
    location_code: 2818,
    location_name: "Egypt",
    location_code_parent: null,
    country_iso_code: "EG",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google", "amazon"],
        language_name: "Arabic",
        language_code: "ar",
        keywords: 27883683,
        serps: 2445068,
      },
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 14832887,
        serps: 1060852,
      },
    ],
  },
  {
    location_code: 2826,
    location_name: "United Kingdom",
    location_code_parent: null,
    country_iso_code: "GB",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "English",
        language_code: "en",
        keywords: 359576562,
        serps: 34365666,
      },
    ],
  },
  {
    location_code: 2840,
    location_name: "United States",
    location_code_parent: null,
    country_iso_code: "US",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google", "bing", "amazon"],
        language_name: "English",
        language_code: "en",
        keywords: 945393725,
        serps: 189737551,
      },
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 117751600,
        serps: 5752634,
      },
    ],
  },
  {
    location_code: 2854,
    location_name: "Burkina Faso",
    location_code_parent: null,
    country_iso_code: "BF",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "French",
        language_code: "fr",
        keywords: 4014074,
        serps: 499281,
      },
    ],
  },
  {
    location_code: 2858,
    location_name: "Uruguay",
    location_code_parent: null,
    country_iso_code: "UY",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 10405821,
        serps: 514121,
      },
    ],
  },
  {
    location_code: 2862,
    location_name: "Venezuela",
    location_code_parent: null,
    country_iso_code: "VE",
    location_type: "Country",
    available_languages: [
      {
        available_sources: ["google"],
        language_name: "Spanish",
        language_code: "es",
        keywords: 39932995,
        serps: 2391827,
      },
    ],
  },
];